INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cisacqgg','et eros vestibulum ac','Lulu on the Bridge','2007-11-11','2024-03-31');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dharkencw','pharetra magna vestibulum aliquet ultrices','Escuela de seducción','2008-07-14','2025-06-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('apickerelljs','aliquet ultrices','AmericanEast','2001-10-14','2024-04-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wnegalfe','consectetuer adipiscing','Viagem a Portugal','2019-10-25','2023-12-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ptwellni','luctus nec molestie','ChubbChubbs!, The','1985-04-11','2024-12-27');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tsaterthwaitik','eget elit sodales scelerisque','Brothers, The','2006-05-15','2023-09-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mshepheardi6','quis tortor id nulla ultrices','Up!','1984-07-25','2023-06-24');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rbarwack1e','auctor sed','Jack Frost','1988-07-19','2022-03-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kcadalleder5','ultrices posuere cubilia','Tatsumi','1982-08-24','2024-05-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jpicktonb4','enim in tempor turpis nec','Last Time I Saw Archie, The','2006-11-10','2023-07-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bbantockch','consectetuer','Kolya (Kolja)','1996-02-21','2023-10-28');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('esilkston5i','facilisi cras non velit','Other People''s Money','1989-07-06','2022-07-27');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('faldin2e','primis in faucibus orci luctus','Lonely Man, The','2019-10-29','2024-07-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cnolleaub2','duis at velit','Strip-tease','1983-09-07','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('krosenau9m','proin interdum mauris','Shoot on Sight','2001-12-22','2023-08-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wvittelg0','a ipsum integer a','Smokey and the Bandit','1992-07-27','2022-12-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('swerlockhc','aliquet maecenas leo','Bob Roberts','2014-04-17','2024-04-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cplayleic','ac tellus semper','This Is the Night','2014-01-31','2023-12-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tbyattap','platea dictumst','Windows','1999-07-26','2023-02-24');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lrawnsley8i','fusce posuere felis sed lacus','College Road Trip','2017-06-11','2024-04-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lpescotthv','pretium iaculis diam erat fermentum','Iron Will','2015-10-22','2023-10-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hlembrickiq','nulla','Erin Brockovich','1992-06-27','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gasplandr7','convallis','Solitary Man','2010-03-19','2023-01-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('adalliganme','dolor sit amet consectetuer adipiscing','Repo! The Genetic Opera','2004-07-09','2022-11-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gspadaro73','duis','More Than a Game','2018-05-22','2023-02-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('swerlockhc','aliquet maecenas leo','Naked Blood: Megyaku (Nekeddo burâddo: Megyaku)','1990-11-30','2024-04-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ccaughte7l','nunc','Santa Fe Trail','2008-03-13','2023-11-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('chopewell84','massa','Blood Runs Cold','1987-11-17','2023-10-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jdelap96','dolor sit amet consectetuer adipiscing','Paradise Alley','2015-01-16','2022-11-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bzannelioh','amet','The Real Glory','2003-03-17','2025-04-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('eparminterg6','donec ut dolor morbi vel','Strange Circus (Kimyô na sâkasu)','2019-02-23','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('amckea5x','faucibus accumsan odio curabitur','Spirits of the Dead','1990-07-19','2023-06-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sbilboroughjr','sapien cursus vestibulum','Crush','2010-02-06','2025-01-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dpalfreemanbx','nunc viverra','Way of the Dragon, The (a.k.a. Return of the Dragon) (Meng long guo jiang)','1996-02-27','2023-07-30');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ogriffe2b','sem praesent id','Full Moon in Paris (Les nuits de la pleine lune)','2007-11-05','2023-04-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dwatts1v','non interdum in','Same Time, Next Year','1991-12-18','2024-03-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rplutherobd','consectetuer adipiscing','47 Ronin, The (Genroku Chûshingura)','1982-04-20','2023-12-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lpullff','amet lobortis sapien sapien','Bellissima','1992-02-02','2023-11-10');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('amckea5x','faucibus accumsan odio curabitur','Boca','2003-04-05','2023-06-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ymcauslene9z','justo nec condimentum','Sanatorium','1992-01-22','2024-02-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fboamea1','proin interdum mauris','Miracle in Cell No. 7','2005-11-04','2023-08-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lkimbroughj3','pretium','Last Remake of Beau Geste, The','1997-08-27','2022-04-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbroadey7w','tincidunt eget','I Accuse','2015-05-05','2022-09-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dlehr8a','ultricies','Wake of the Red Witch','1984-10-29','2023-06-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rsmouten3a','proin interdum mauris','Green Chair (Noksaek uija)','2005-02-28','2023-08-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('akettjs','vel accumsan','American Raspberry (Prime Time) (Funny America)','2008-12-31','2025-08-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mmanifouldg1','suspendisse ornare consequat','Deadtime Stories','1985-07-31','2024-05-07');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('craimbauldp0','lacus at velit vivamus','Dead or Alive: Hanzaisha','2013-07-24','2023-10-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fmanifoldrk','tempus semper est quam pharetra','Chasing Liberty','2014-08-02','2023-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cmaggillandreis9o','primis in faucibus orci','Halloween III: Season of the Witch','1992-12-11','2023-09-27');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('socarrolel','eu est','Wanderlust','2008-08-20','2025-02-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rmittone8','nisl nunc rhoncus','Bonjour Monsieur Shlomi (Ha-Kochavim Shel Shlomi)','2014-10-18','2024-03-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('aaylettnn','at turpis','Little Ashes','1987-12-03','2022-02-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rsheddgq','dui','Kumaré','1980-05-16','2025-02-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('askipseyp6','nulla','Revenge of the Nerds IV: Nerds in Love','1995-07-22','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lpullff','amet lobortis sapien sapien','Rasputin and the Empress','1981-06-29','2023-11-10');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rkneaphseyk7','nulla eget eros elementum','It Started with Eve','1997-08-26','2024-07-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('afludgatehm','rutrum neque aenean auctor','Taxi Driver','1998-05-29','2022-07-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wmattamrl','morbi porttitor lorem id ligula','Lonely Street','1997-10-29','2022-11-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hsimoneschi5x','elementum nullam varius','Imagine','1986-04-05','2024-01-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astrivensmf','velit vivamus','Sazen Tange and the Pot Worth a Million Ryo','1986-09-04','2024-02-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cportsmouth3h','in hac habitasse platea','Funky Forest: The First Contact','1986-03-02','2025-05-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbeacockr3','diam id ornare imperdiet','World According to Dick Cheney, The','1984-03-21','2025-05-07');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ethomtson5u','nullam molestie nibh in','Garage Sale Mystery','2015-03-27','2023-06-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mtayntonbb','donec diam','Witches, The (Le streghe)','1998-09-28','2025-04-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lsturdeyer','id nulla ultrices aliquet maecenas','Zigeunerweisen (Tsigoineruwaizen)','1981-04-16','2024-03-30');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tdevericksqp','mauris','Johnny Express','2005-10-02','2025-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ethomtson5u','nullam molestie nibh in','Woo','1995-12-11','2023-06-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbricket18','curabitur at ipsum','Final Destination 5','2014-10-26','2024-03-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cportsmouth3h','in hac habitasse platea','War Made Easy: How Presidents & Pundits Keep Spinning Us to Death','1984-08-16','2025-05-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lhyattr6','primis','The Substitute 2: School''s Out','1998-06-08','2022-05-21');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sbilboroughjr','sapien cursus vestibulum','Who the #$&% is Jackson Pollock?','1990-06-16','2025-01-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gfrearsonji','ac leo','Fatherland','2009-08-30','2025-02-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mrobkeni5','in','Batman/Superman Movie, The','1985-11-26','2023-05-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ituckermanqg','mauris morbi non lectus','Pervert''s Guide to Ideology, The','1984-10-08','2023-01-08');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mscroobyf5','vel augue vestibulum','Rising Sun','1983-06-05','2023-02-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lreddyhoffi3','integer','Simple Life of Noah Dearborn, The','2008-08-28','2024-05-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('khillbornefp','at','The Last Time I Saw Macao','1993-09-30','2022-07-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gwardinglyes','semper porta volutpat quam pede','Hansel & Gretel: Witch Hunters','2019-05-03','2023-06-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gsomerlie1e','sed justo pellentesque viverra pede','Cat People','2019-04-11','2025-04-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tbyattap','platea dictumst','Malèna','1983-03-19','2023-02-24');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('eaudrittn7','donec ut dolor morbi vel','40 Guns to Apache Pass','1995-05-23','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('apayleyd8','mattis nibh ligula nec sem','Operation Mad Ball','2006-05-23','2025-02-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jhanigan54','sociis natoque penatibus et','Lay the Favorite','1988-10-19','2023-02-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tbanthorpemf','tincidunt lacus','Nightmare Alley','1991-09-14','2024-02-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bduckwithce','amet cursus','Assassin Next Door, The (Kirot)','1980-12-16','2023-06-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bstayti7','libero quis orci nullam','Crackerjack','2000-06-25','2023-02-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('eaudrittn7','donec ut dolor morbi vel','Highway to Hell','2011-01-27','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mschermickfg','elementum nullam varius','House of Sand and Fog','1984-12-12','2024-01-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mtayntonbb','donec diam','Ruins, The','1989-08-19','2025-04-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('posbournn1','ut volutpat','Charlie''s Country','2009-05-01','2024-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fgalland1h','porta','Woman''s Face, A (En kvinnas ansikte)','1982-10-19','2025-10-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jvassarqa','tellus nisi','Rebirth of Mothra II','1988-11-21','2023-02-23');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('nshearerp5','donec ut dolor morbi vel','Extraordinary Adventures of Adèle Blanc-Sec, The','2008-05-14','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mmurfin5z','in felis eu','Beethoven''s Treasure Tail','1984-01-08','2024-09-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('scompsonhe','facilisi cras non velit','Condition Red (Beyond the Law)','1996-02-23','2022-07-27');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ttiversid','magna','Gett: The Trial of Viviane Amsalem','1981-01-16','2022-11-08');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tdevericksqp','mauris','Return of Doctor X, The','2001-04-13','2025-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gvaughten6x','et eros vestibulum ac','Bang Bang','1983-03-23','2024-03-31');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rmacafee3t','sapien varius ut blandit','Rugrats Movie, The','2016-07-25','2022-03-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kganniclifftgo','luctus ultricies eu nibh quisque','S.P.L.: Kill Zone (Saat po long)','1994-03-26','2023-02-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ktessington90','in felis eu','Dirty Filthy Love','1994-04-05','2024-09-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mrobkeni5','in','Venus Boyz','2016-04-29','2023-05-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dbaxns','posuere nonummy integer non','Molly Maxwell','2018-06-26','2023-05-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astrivensmf','velit vivamus','Last Days in the Desert','2007-07-06','2024-02-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('btarboxdu','dictumst etiam faucibus cursus urna','Stakeout','2010-01-07','2024-07-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cfarlhampu','consectetuer adipiscing','Central Park','1980-09-16','2023-12-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('odenny5s','non quam nec dui','Cell 2, The','1984-12-14','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lrandsl4','amet cursus','Going Overboard','1981-09-13','2023-06-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cskoggins7e','justo in blandit','Children of Invention','1996-08-18','2022-10-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rheusticeh5','massa id lobortis convallis tortor','The Bride Wore Red','2012-02-29','2024-05-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kburnei9','nulla','Night of the Day of the Dawn of the Son of the Bride of the Return of the Terror','2001-03-14','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fbeattie5q','in','Swimsuit Issue, The (Allt flyter)','1994-03-18','2023-02-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ccoxallnv','non pretium','Joe Kidd','2017-04-06','2024-12-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sglentworth3t','nulla','Die Fischerin','2002-12-28','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kganniclifftgo','luctus ultricies eu nibh quisque','Life in a Day','1987-07-08','2023-02-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fsteel89','amet','Win/win','1985-12-20','2024-01-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbonin7v','dictumst aliquam augue quam','Wild Love','2004-07-06','2023-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bseagood4s','lacus curabitur at ipsum','Red Eye','1987-03-15','2025-01-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lcanbyj5','proin','Strike Up the Band','2016-10-16','2022-12-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ymcauslene9z','justo nec condimentum','Order, The','1995-07-20','2024-02-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dstonep','pede justo','Old Man and the Sea, The','2004-11-03','2022-09-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rheusticeh5','massa id lobortis convallis tortor','Sea Wolf, The','1999-09-24','2024-05-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('amoldends','duis at velit','At the River I Stand','1986-04-11','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ibeazerex','nisl nunc','This Man Must Die (Que la bête meure)','2009-09-09','2025-04-12');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ckunertr8','faucibus cursus urna ut','Skylark','2009-10-25','2024-01-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wmccandiel7','pretium iaculis diam erat fermentum','Escape from L.A.','1981-12-03','2023-10-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bfishwickau','praesent blandit nam nulla integer','Manito','1980-02-24','2024-08-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gjanowiczgn','tincidunt lacus','Quai des Orfèvres (Jenny Lamour)','2014-10-10','2024-02-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fpaddockih','luctus rutrum nulla','My Date with Drew','1990-05-21','2025-06-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('awestwickhv','metus','Blind Side, The','1981-05-03','2023-06-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('switton7s','nullam molestie nibh in','Eden Log','2013-03-16','2023-06-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('stiversqb','posuere cubilia curae','Joysticks','1987-04-22','2025-08-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ccolesmq','libero quis orci nullam','Family Game, The (Kazoku gêmu)','1988-08-19','2023-02-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('spedrozzih5','nisl nunc rhoncus','Canterbury Tale, A','1990-05-24','2024-03-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rsolesrg','massa volutpat convallis morbi','Sumo Do, Sumo Don''t (Shiko funjatta)','1980-10-25','2022-09-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('coloughlin6p','morbi vestibulum velit id','There''s a Girl in My Soup','1981-04-11','2024-05-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbeacockr3','diam id ornare imperdiet','Kozara','2011-08-08','2025-05-07');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('emcmenaminh6','mattis nibh ligula nec sem','Night Will Fall','1992-10-02','2025-02-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rsmouten3a','proin interdum mauris','House of Games','2011-04-14','2023-08-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kseneschala','vehicula condimentum curabitur','Hungarian Fairy Tale, A (Hol volt, hol nem volt)','1982-12-15','2024-09-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tlaughlin2c','magna','Licence to Kill','2001-09-14','2022-11-08');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rbridgestock9i','donec ut dolor morbi','Winter of Frozen Dreams','2011-05-03','2022-03-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dkohenp8','id','Je préfère qu''on reste amis','2019-08-15','2022-07-28');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('llavistege','proin eu mi','Shanghai Gesture, The','1996-03-07','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bduckwithce','amet cursus','Reflections in a Golden Eye','1987-08-12','2023-06-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('myoude87','sem duis aliquam convallis nunc','Aloha Summer','2002-05-10','2023-06-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lsturdeyer','id nulla ultrices aliquet maecenas','Remember Me','2005-02-10','2024-03-30');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fbeattie5q','in','Zatoichi''s Flashing Sword (Zatôichi abare tako) (Zatôichi 7)','1996-01-14','2023-02-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ifinlanjc','massa volutpat convallis morbi','Cause for Alarm!','1981-05-14','2022-09-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mlergan9a','pellentesque','Winning Streak','2017-09-20','2024-06-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rhelianaq','eu est','Trauma','1996-02-25','2025-02-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mruppertzrj','amet nulla quisque arcu','Monsieur Verdoux','2013-06-12','2023-07-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbricket18','curabitur at ipsum','Starship Troopers 3: Marauder','2005-08-26','2024-03-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('pocorrenfw','odio','Wheel of Time','2015-09-28','2025-06-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lhyattr6','primis','Flightplan','2010-05-20','2022-05-21');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gsouthwayc4','convallis','Flame and Women (Honô to onna)','2000-09-03','2023-01-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sglentworth3t','nulla','Relic, The','1985-11-03','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bboddymead9s','a libero nam dui','Battle of Britain','1982-08-23','2023-11-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tneward63','rhoncus dui vel sem sed','Yank in the R.A.F., A','2015-02-01','2025-06-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('qdunstonebv','pretium','Pan Tadeusz: The Last Foray in Lithuania (Pan Tadeusz)','2000-04-27','2022-04-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('smuirdenq2','odio porttitor','Santa with Muscles','1992-11-17','2023-07-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('vstachiniqz','aliquet ultrices','Hansel & Gretel: Witch Hunters','2019-05-03','2024-04-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('chopewell84','massa','Cool as Ice','2002-08-21','2023-10-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wfateley6t','vehicula condimentum curabitur in libero','Breed, The','1981-08-19','2023-11-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('alombgx','faucibus accumsan odio curabitur','Spitfire Grill, The','2004-06-02','2023-06-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cportsmouth3h','in hac habitasse platea','Return of Doctor X, The','2001-04-13','2025-05-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hburgott60','aliquet maecenas leo','Assassination','1982-12-23','2024-04-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fbeattie5q','in','Like Father, Like Son (Soshite chichi ni naru)','1983-05-23','2023-02-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mlandsburyg9','orci','Music in the Air','1983-04-22','2024-10-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('avanderspohr6','est risus','Court-Martial of Billy Mitchell, The','2016-09-25','2025-06-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mvinallbl','sed tristique in tempus','Hungarian Fairy Tale, A (Hol volt, hol nem volt)','1982-12-15','2024-01-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('thorchec4','erat fermentum justo','Batman/Superman Movie, The','1985-11-26','2022-04-12');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hshiel12','lorem integer tincidunt','Yes Or No','1991-05-21','2024-04-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bgussin4f','volutpat dui maecenas tristique est','Mean Guns','2004-02-27','2024-11-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dbolsteridgehj','mattis pulvinar nulla pede','All''s Faire in Love','1985-12-30','2023-04-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('alowryeg','in hac habitasse','Invaders from Space','2014-12-01','2025-02-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dmacallami0','non quam nec dui','Zorro','2006-01-04','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tkinson5h','ornare consequat lectus','The Day That Lasted 21 Years','1986-03-15','2024-10-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tlivesey4a','pede justo','Traveller','1993-06-20','2022-09-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lgrogonapq','adipiscing','East Side Story','1990-05-12','2024-09-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astonaryq5','congue eget semper rutrum nulla','Senseless','1996-07-11','2023-10-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fgalland1h','porta','Good, the Bad, the Weird, The (Joheunnom nabbeunnom isanghannom)','1988-09-28','2025-10-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gkainzpo','dictumst aliquam augue quam','Holy Flame of the Martial World (Wu lin sheng huo jin)','1997-07-24','2023-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mkorng3','sapien varius ut blandit','Babylon 5: The Gathering','1986-06-19','2022-03-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('acarer1','non quam nec dui','Other People''s Money','1989-07-06','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cgageg','lectus in quam fringilla','Beginning of the Great Revival (a.k.a. The Founding of a Party)','2002-10-10','2025-07-07');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astairsk','congue diam id ornare imperdiet','There''s a Girl in My Soup','1981-04-11','2022-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fboamea1','proin interdum mauris','Riot on Sunset Strip','2015-12-04','2023-08-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mloinesrh','consectetuer','Kika','1992-07-31','2023-10-28');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sbilboroughjr','sapien cursus vestibulum','Milk Money','2006-06-20','2025-01-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wbeels2c','id pretium iaculis','I Heart Huckabees','1986-06-24','2024-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tmalangb','pulvinar lobortis est','Strike Up the Band','2016-10-16','2023-09-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gwhitneyh0','odio','Whores'' Glory','1986-02-15','2025-06-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wharbisonmz','turpis elementum ligula','Ask Me Anything','2011-09-10','2024-05-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gwhitneyh0','odio','Smokers Only (Vagón Fumador)','1995-03-24','2025-06-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ethoriusqq','scelerisque mauris sit','Veer Zaara','2017-03-13','2024-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kcadalleder5','ultrices posuere cubilia','Charlie Victor Romeo','1991-07-15','2024-05-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jsprouleme','fusce consequat nulla nisl','State Property','1997-05-31','2023-08-24');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('naubin9c','faucibus orci luctus et ultrices','Strip-tease','1983-09-07','2024-09-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gradbond5o','congue etiam','Surfer, Dude','1993-04-27','2024-09-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dpalfreemanbx','nunc viverra','Drawn Together Movie: The Movie!, The','2002-04-08','2023-07-30');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('btarboxdu','dictumst etiam faucibus cursus urna','Bunch Of Amateurs, A','1992-04-13','2024-07-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dgurnerdq','penatibus et magnis','Wish Me Away','2017-04-11','2022-08-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mgleadle6z','consequat lectus in est','Hank and Mike','2012-03-04','2024-11-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dwatts1v','non interdum in','Bigfoot','2005-03-10','2024-03-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ethoriusqq','scelerisque mauris sit','Count Yorga, Vampire','2008-01-31','2024-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('woverhu','est risus','BASEketball','2002-09-06','2025-06-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wfateley6t','vehicula condimentum curabitur in libero','Diverted','2006-11-03','2023-11-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('redgerl','mauris','Faraway, So Close (In weiter Ferne, so nah!)','2008-03-16','2024-10-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('leveralj2','et eros vestibulum ac','Last Lions, The','2019-09-03','2024-03-31');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astonaryq5','congue eget semper rutrum nulla','Just Like Us','1987-07-21','2023-10-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('amckea5x','faucibus accumsan odio curabitur','Kid Millions','2018-03-07','2023-06-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('alawief0','enim sit','MacGyver: Trail to Doomsday','2003-03-01','2025-04-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('amoldends','duis at velit','Death of a Nation - The Timor Conspiracy','2000-11-22','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbirtwisle27','congue diam id ornare imperdiet','Lonesome Dove','2000-04-30','2022-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('krosenau9m','proin interdum mauris','Sniper: Reloaded','2012-07-24','2023-08-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cplayleic','ac tellus semper','Bonnie Scotland (Heroes of the Regiment)','1985-03-11','2023-12-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kburnei9','nulla','Boca','2003-04-05','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cionsfk','congue eget semper rutrum nulla','Corn Island (Simindis kundzuli)','1993-06-17','2023-10-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('awestphalmq','dolor sit amet consectetuer adipiscing','Home Run','1981-05-06','2022-11-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jcroslandgc','massa','Superman II','2004-08-06','2023-10-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gkainzpo','dictumst aliquam augue quam','Harper Valley P.T.A.','1980-08-28','2023-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dbrierleyhr','velit vivamus','Three Faces of Eve, The','1999-02-20','2024-02-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sbilboroughjr','sapien cursus vestibulum','Soloalbum','2001-03-18','2025-01-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ckunertr8','faucibus cursus urna ut','Amazing Grace and Chuck','2012-03-01','2024-01-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('giowarchd2','nonummy','Wild Animals (Yasaeng dongmul bohoguyeog)','2006-10-13','2025-03-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bsiehardrh','nec sem duis','Soldier''s Girl','1995-11-24','2023-07-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('qdunstonebv','pretium','Gator','1984-08-07','2022-04-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('twhitten7n','montes nascetur ridiculus mus','Hiding Cot (Piilopirtti)','2001-11-06','2023-09-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('acrosscombecs','faucibus orci luctus et ultrices','Where Danger Lives','2012-01-14','2024-09-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('acrosscombecs','faucibus orci luctus et ultrices','Meet the Spartans','2016-04-21','2024-09-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('drennyck','at','Assassination (Ansatsu) (Assassination, The) (Assassin, The)','2007-05-13','2022-07-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jcressorpt','cursus id turpis integer aliquet','Sinbad (Szindbád)','2016-10-31','2025-06-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('twhitten7n','montes nascetur ridiculus mus','Broadway Melody of 1938','2007-02-14','2023-09-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cledgistercp','tellus','House on 92nd Street, The','2014-12-18','2024-10-24');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dsutehall9r','est risus','Shoppen','2003-05-24','2025-06-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bsouthby13','at ipsum','Funky Forest: The First Contact','1986-03-02','2023-01-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('craimbauldp0','lacus at velit vivamus','Kentucky Fried Movie, The','2004-04-15','2023-10-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('arueggr6','quam fringilla rhoncus','Blues Brothers 2000','1980-07-20','2024-04-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ftavenerpc','odio in','Las Vegas Story, The','1992-01-19','2022-08-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('eeykelboschdz','diam nam tristique tortor eu','The Magic Box','1994-11-07','2025-07-08');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mkiosselbh','donec ut dolor morbi vel','In Secret','1987-12-06','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ddiwell62','congue diam id ornare imperdiet','Bear, The (Ours, L'')','1995-12-24','2022-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dthrossell39','pede ac diam','Sea Wolf, The','1999-09-24','2023-10-24');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cfarlhampu','consectetuer adipiscing','Solino','2014-10-13','2023-12-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cweatherillkm','dictumst aliquam augue quam','Brown Sugar','2009-12-28','2023-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('eaudrittn7','donec ut dolor morbi vel','Fire Down Below','2006-06-05','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dkohenp8','id','O','2000-09-25','2022-07-28');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ddiwell62','congue diam id ornare imperdiet','Tombs of the Blind Dead (La noche del terror ciego)','1997-05-06','2022-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ggrimmertgj','vestibulum sed magna at','Muddy River','1984-07-15','2023-03-31');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dblaisdellgv','non pretium','Shame','2003-06-30','2024-12-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('xvarrowng','vel augue vestibulum','Laila','2004-05-20','2023-02-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mportwaine7f','duis at velit','Children of Dune','1983-02-22','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rmclellandn2','magna','Mr. Popper''s Penguins','1983-08-06','2022-11-08');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('smuirdenq2','odio porttitor','Ninotchka','1990-09-23','2023-07-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('abristowe8','condimentum curabitur','The Karen Carpenter Story','1996-05-12','2023-06-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fkastingeg','quam a odio in','Happy Gilmore','2011-08-05','2024-04-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('qdunstonebv','pretium','12 Angry Men','2016-03-14','2022-04-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mrobkeni5','in','Criminal','1985-07-15','2023-05-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('vtriggolfh','aliquet maecenas leo','Green Chair (Noksaek uija)','2005-02-28','2024-04-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ktessington90','in felis eu','Sophie Scholl: The Final Days (Sophie Scholl - Die letzten Tage)','1988-09-06','2024-09-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('khillbornefp','at','Altered','1998-09-29','2022-07-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mmanifouldg1','suspendisse ornare consequat','Grave Encounters','1987-10-18','2024-05-07');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mlergan9a','pellentesque','Black Rock','1991-08-01','2024-06-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ibeazerex','nisl nunc','Nothing to Lose','2005-06-16','2025-04-12');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tsaterthwaitik','eget elit sodales scelerisque','Losers'' Club (Kaybedenler kulübü)','1991-07-24','2023-09-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ccaughte7l','nunc','Texas Chainsaw Massacre: The Next Generation (a.k.a. The Return of the Texas Chainsaw Massacre)','2013-01-31','2023-11-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kcadalleder5','ultrices posuere cubilia','Mystery of the Third Planet, The (Tayna tretey planety)','2002-09-08','2024-05-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gjoslandqv','vehicula condimentum curabitur','Deal of the Century','2008-03-10','2024-09-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ndevallew','consectetuer adipiscing','Kai Po Che!','1987-10-26','2023-12-20');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('myoude87','sem duis aliquam convallis nunc','Star Trek III: The Search for Spock','2016-11-27','2023-06-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bsiehardrh','nec sem duis','It''s My Party','1989-07-22','2023-07-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bgarmstoni4','est lacinia','Last Call at the Oasis','1988-02-20','2023-04-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gasplandr7','convallis','Supporting Characters','1990-11-18','2023-01-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hjovici2','at turpis','Pentimento','2000-07-02','2022-02-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rsare9m','congue eget semper rutrum nulla','The Diary of Anne Frank','1994-01-09','2023-10-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mkiosselbh','donec ut dolor morbi vel','Sazen Tange and the Pot Worth a Million Ryo','1986-09-04','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kstoffersen1g','pellentesque','Fetishes','1997-07-26','2024-06-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mhattermg','augue','Bonnie and Clyde','2008-04-26','2023-08-28');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('srevetth2','mollis','Gabriel','2016-12-12','2025-01-21');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lrawnsley8i','fusce posuere felis sed lacus','Sweet and Lowdown','1999-06-20','2024-04-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('elucien3o','in hac habitasse platea','Nobody Walks','1984-12-11','2025-05-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bseagood4s','lacus curabitur at ipsum','ChubbChubbs!, The','1985-04-11','2025-01-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('apolsinin','vehicula consequat morbi a','Secret Life of Zoey, The','2007-10-30','2024-04-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bboddymead9s','a libero nam dui','City Slacker','1987-03-04','2023-11-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gfrearsonji','ac leo','Dancing in the Rain (Ples v dezju)','1984-02-12','2025-02-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mskillittj2','sollicitudin vitae consectetuer','With Six You Get Eggroll','1992-07-15','2023-06-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ttiversid','magna','Alamo, The','1982-11-14','2022-11-08');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hlembrickiq','nulla','Telling You','1995-06-05','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ccaughte7l','nunc','Ponyo (Gake no ue no Ponyo)','2014-12-29','2023-11-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('adyethy','duis at velit','Army of Crime (L''armée du crime)','2011-12-15','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cskoggins7e','justo in blandit','Acid House, The','2006-04-18','2022-10-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wpashencr','tellus in sagittis dui vel','Song of the Exile (Ke tu qiu hen)','1998-04-10','2025-01-14');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lrawnsley8i','fusce posuere felis sed lacus','Man Who Quit Smoking, The (Mannen som slutade röka)','2015-12-18','2024-04-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rsolesrg','massa volutpat convallis morbi','Marc Maron: Thinky Pain','2019-05-20','2022-09-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jpicktonb4','enim in tempor turpis nec','Philadelphia Experiment, The','2016-04-29','2023-07-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bduckwithce','amet cursus','Home','2013-03-14','2023-06-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cglassupcn','est lacinia nisi venenatis','Entity','2018-07-24','2022-09-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tlivesey4a','pede justo','Evening','2002-05-18','2022-09-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hreiskpd','aliquet','Shot in the Heart','2012-03-05','2022-02-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mdamerellfy','nisl nunc rhoncus dui vel','In the Loop','2013-11-05','2024-05-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gwicher11','tortor quis turpis sed ante','Little Voice','2017-08-23','2024-07-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lcanbyj5','proin','Shark Alarm at Müggelsee (Hai Alarm am Müggelsee)','1998-09-15','2022-12-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mrobkeni5','in','Wake of the Red Witch','1984-10-29','2023-05-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ehinckley5p','mattis nibh ligula','Starship Troopers 3: Marauder','2005-08-26','2023-05-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mbirtwisle27','congue diam id ornare imperdiet','Lorna''s Silence (Le silence de Lorna)','2001-05-24','2022-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dhawketl1','amet lobortis sapien sapien','Great Directors','2010-05-07','2023-11-10');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astrivensmf','velit vivamus','In the Soup','2002-08-21','2024-02-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dbredgeland92','nec sem duis','Kelly''s Heroes','1998-04-01','2023-07-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ccolesmq','libero quis orci nullam','12 Dates of Christmas','2003-07-04','2023-02-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kcadalleder5','ultrices posuere cubilia','Defender, The (a.k.a. Bodyguard from Beijing, The) (Zhong Nan Hai bao biao)','1986-01-09','2024-05-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('switton7s','nullam molestie nibh in','Fortune Cookie, The','1987-06-03','2023-06-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wvittelg0','a ipsum integer a','Silvestre','1983-05-21','2022-12-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('posbournn1','ut volutpat','Fear and Trembling (Stupeur et tremblements)','1995-11-19','2024-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gspadaro73','duis','Innocent Voices (Voces inocentes)','1996-05-02','2023-02-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bfishwickau','praesent blandit nam nulla integer','Giliap','1984-02-07','2024-08-13');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jchaineyjq','nullam molestie nibh in','The Adventures of Tom Thumb & Thumbelina','1990-03-03','2023-06-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gnairyrb','non quam nec dui','Last House on the Left, The','1981-03-11','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astonaryq5','congue eget semper rutrum nulla','Willow Creek','1986-06-06','2023-10-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hdelouchfh','mattis pulvinar nulla pede','Trailer Park Jesus','2011-01-09','2023-04-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cweatherillkm','dictumst aliquam augue quam','Decameron, The (Decameron, Il)','2001-12-24','2023-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hshiel12','lorem integer tincidunt','Hungry for Change','2003-08-09','2024-04-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rmittone8','nisl nunc rhoncus','Sniper: Reloaded','2012-07-24','2024-03-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lrawnsley8i','fusce posuere felis sed lacus','Reach the Rock','1989-01-06','2024-04-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tmansion2w','turpis elementum ligula vehicula','Tales of the Grim Sleeper','2008-08-21','2024-04-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('jpicktonb4','enim in tempor turpis nec','And Then Came Lola','1987-09-05','2023-07-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hjovici2','at turpis','Get Thrashed: The Story of Thrash Metal','1995-08-20','2022-02-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tjorrylf','porttitor lacus at turpis','East Meets West (Dung sing sai tsau 2011)','1984-03-28','2023-08-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ggrimmertgj','vestibulum sed magna at','Endgame','1986-06-03','2023-03-31');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bsouthby13','at ipsum','Bostonians, The','1989-08-08','2023-01-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('pmacswaydeox','curabitur at ipsum','Wise Guys, The (Les grandes gueules)','2000-12-23','2024-03-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('adyethy','duis at velit','Waking Up in Reno','1998-07-18','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('afludgatehm','rutrum neque aenean auctor','Food Matters','1989-06-13','2022-07-02');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wwhitehurst6u','blandit lacinia erat vestibulum sed','Rosewater','1996-09-03','2024-02-07');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('creviehb','aliquet maecenas leo','Notorious','1995-10-07','2024-04-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('challstonei1','vestibulum','Elia Kazan: A Director''s Journey','1991-06-06','2022-11-22');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hsimoneschi5x','elementum nullam varius','Beethoven''s Treasure Tail','1984-01-08','2024-01-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gkainzpo','dictumst aliquam augue quam','Honey, I Blew Up the Kid','2015-02-14','2023-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('acrossgrovejn','cursus id','Factory, The','2012-12-10','2022-09-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('llavistege','proin eu mi','If Footmen Tire You What Will Horses Do?','2001-03-26','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hjovici2','at turpis','Hell and Back Again','2012-09-09','2022-02-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('fmanifoldrk','tempus semper est quam pharetra','Deux mondes, Les','1985-11-22','2023-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mfalla7t','vestibulum aliquet','My Flesh My Blood (Moja krew)','2004-03-10','2023-03-19');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rlinklu','nunc viverra','Falcon and the Snowman, The','1984-09-13','2023-07-30');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dblaisdellgv','non pretium','Shadow of the Thin Man','2001-02-16','2024-12-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('adunkerly8i','fermentum donec ut mauris eget','Rabbit Test','2014-08-18','2025-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('amoldends','duis at velit','Rhyme & Reason','2001-03-17','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('chullrn','est risus','All''s Faire in Love','1985-12-30','2025-06-04');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('astairsk','congue diam id ornare imperdiet','Bloody Pit of Horror (Il boia scarlatto) (Virgins for the Hangman)','1989-12-02','2022-03-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cnolleaub2','duis at velit','Most Dangerous Game, The','2018-03-31','2024-01-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cglassupcn','est lacinia nisi venenatis','Hamlet Goes Business (Hamlet liikemaailmassa)','2010-10-21','2022-09-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bboddymead9s','a libero nam dui','Ghost Rider: Spirit of Vengeance','2009-01-02','2023-11-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('esilkston5i','facilisi cras non velit','Moment by Moment','1987-02-08','2022-07-27');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sgreser8n','aliquet ultrices erat tortor','Two Rabbits (2 Coelhos)','1980-05-11','2023-05-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ufenelon8j','nascetur ridiculus mus','Blank City','1990-02-03','2025-08-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('giowarchd2','nonummy','Jacknife','2004-10-24','2025-03-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('acrosscombecs','faucibus orci luctus et ultrices','Haunting in Connecticut, The','2016-06-25','2024-09-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gnairyrb','non quam nec dui','I''ll See You in My Dreams','1995-05-29','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lpullff','amet lobortis sapien sapien','Now You See Him, Now You Don''t','2010-11-08','2023-11-10');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ndiessll','ut','Me and Morrison (Minä ja Morrison)','2002-02-07','2024-05-29');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('knystrom7a','quam fringilla rhoncus mauris','Regular Guys (Echte Kerle)','2010-10-27','2023-08-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lpenwardenpy','sed justo pellentesque viverra pede','Flying Swords of Dragon Gate, The (Long men fei jia)','2016-04-01','2025-04-16');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('hjovici2','at turpis','Pan Tadeusz: The Last Foray in Lithuania (Pan Tadeusz)','1994-02-14','2022-02-05');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tedelermu','semper porta volutpat quam pede','Fool for Love','1997-06-05','2023-06-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('dbredgeland92','nec sem duis','Apartment 4E','2015-06-08','2023-07-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('acarer1','non quam nec dui','Eddie Izzard: Force Majeure Live','1987-12-11','2023-05-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cblackledgeom','tortor quis turpis sed ante','Last Polka, The','2005-09-23','2024-07-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('eparminterg6','donec ut dolor morbi vel','Billy the Kid','1998-10-15','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bgoskerq7','fusce posuere felis sed lacus','8 1/2 (8½)','2016-03-23','2024-04-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('tjorrylf','porttitor lacus at turpis','Sound City','2015-09-06','2023-08-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('lpullff','amet lobortis sapien sapien','Let It Snow','2017-01-14','2023-11-10');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('rlinklu','nunc viverra','Starbuck','1990-07-09','2023-07-30');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ncrown3g','amet justo morbi ut odio','Rise','2018-05-03','2023-06-23');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('vtriggolfh','aliquet maecenas leo','99 and 44/100% Dead','1983-01-09','2024-04-26');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cweatherillkm','dictumst aliquam augue quam','Five-Year Engagement, The','2002-03-29','2023-08-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('krouff3m','a ipsum integer a','Summer with Monika (Sommaren med Monika)','2019-11-22','2022-12-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('ufenelon8j','nascetur ridiculus mus','Spitfire Grill, The','2004-06-02','2025-08-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mschermickfg','elementum nullam varius','Going Berserk','2011-08-12','2024-01-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('amadgin5c','velit vivamus','Maniac Cop','1991-12-30','2024-02-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bgoskerq7','fusce posuere felis sed lacus','Général Idi Amin Dada: A Self Portrait (Général Idi Amin Dada: Autoportrait)','1987-10-30','2024-04-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gneubigin4e','vehicula condimentum curabitur','Schmatta: Rags to Riches to Rags','1981-05-14','2024-09-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('posbournn1','ut volutpat','Pal Joey','2018-08-11','2024-01-06');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('kganniclifftgo','luctus ultricies eu nibh quisque','Story of Vernon and Irene Castle, The','1989-01-21','2023-02-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bsnodaygg','imperdiet nullam orci pede','I Have Found It (Kandukondain Kandukondain)','2008-04-27','2024-04-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gjoslandqv','vehicula condimentum curabitur','Flower & Garnet','1982-05-16','2024-09-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cisacqgg','et eros vestibulum ac','Bend of the River','1999-03-01','2024-03-31');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mgoodspeed3b','faucibus orci luctus et ultrices','Kumaré','1980-05-16','2024-09-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('cglassupcn','est lacinia nisi venenatis','Sound and Fury','2007-03-17','2022-09-17');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('gfrearsonji','ac leo','Max Manus','1980-04-03','2025-02-25');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mgoodspeed3b','faucibus orci luctus et ultrices','Crush','2010-02-06','2024-09-01');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('avandijk5c','curae mauris viverra','Pollyanna','2012-12-09','2025-06-27');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('mschermickfg','elementum nullam varius','Police Python 357','1986-03-04','2024-01-18');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('wphilippet6v','donec ut dolor morbi vel','Lady of Chance, A','1983-04-23','2023-02-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('myoude87','sem duis aliquam convallis nunc','Attack on the Iron Coast','1986-04-08','2023-06-11');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bboddymead9s','a libero nam dui','Disaster L.A.','1981-07-31','2023-11-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('redgerl','mauris','Brother Sun, Sister Moon (Fratello sole, sorella luna)','2015-03-23','2024-10-03');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('sgreser8n','aliquet ultrices erat tortor','Final Fantasy VII: Advent Children','1982-10-17','2023-05-15');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('askipseyp6','nulla','Sound and Fury','1990-07-15','2022-03-09');
INSERT INTO CollectionMovies(username,listName,movieTitle,releaseDate,dateCreated) VALUES ('bgarmstoni4','est lacinia','Rogue Cop','1988-09-14','2023-04-01');
