INSERT INTO Collection(listName,description,dateCreated) VALUES ('in felis eu','Sed accumsan felis.','2024-09-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tellus nisi','Pellentesque ultrices mattis odio.','2023-02-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('faucibus accumsan odio curabitur','In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.','2023-06-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('enim in tempor turpis nec','Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.','2023-07-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('proin interdum mauris non','In quis justo.','2025-02-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('id justo sit','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.','2023-06-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('cursus','Donec semper sapien a libero. Nam dui.','2022-10-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('facilisi cras non','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.','2024-05-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('elementum ligula vehicula','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.','2024-05-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('lobortis est phasellus sit','Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.','2024-02-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('maecenas tristique','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','2022-08-27');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec diam','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.','2025-04-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eu','Aenean fermentum.','2022-03-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('commodo placerat praesent blandit','Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.','2023-09-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('at turpis','Suspendisse potenti.','2022-02-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dui nec nisi','Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.','2022-10-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('congue diam id ornare imperdiet','Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.','2022-03-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('enim sit','Morbi a ipsum. Integer a nibh. In quis justo.','2025-04-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('id ligula suspendisse ornare','Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.','2025-03-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mauris','Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.','2022-09-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('praesent id','Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.','2024-05-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nulla eget eros elementum','Suspendisse accumsan tortor quis turpis. Sed ante.','2024-07-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('metus aenean','Duis at velit eu est congue elementum.','2024-06-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nulla','Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.','2022-03-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('fusce consequat nulla nisl','Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','2023-08-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('augue','Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.','2023-08-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nonummy integer non velit donec','Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.','2023-05-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nullam porttitor lacus at turpis','Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.','2024-07-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('libero quis orci nullam','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.','2023-02-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nunc viverra','Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.','2023-07-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('aliquet','Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.','2022-02-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('velit','Aenean sit amet justo.','2024-12-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('purus','Nam dui.','2023-12-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ut','Nulla justo.','2024-01-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('id pretium iaculis','Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.','2024-01-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.','2024-01-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vel pede','In eleifend quam a odio. In hac habitasse platea dictumst.','2022-10-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('proin','Phasellus in felis. Donec semper sapien a libero.','2022-12-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('luctus et ultrices posuere','Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.','2024-07-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vestibulum ante','Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.','2022-07-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ornare consequat','Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.','2023-01-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('porttitor','Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.','2024-12-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dictumst etiam faucibus cursus urna','Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.','2024-07-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien cursus vestibulum','Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.','2025-01-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ornare consequat lectus','Aenean fermentum.','2024-10-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('at','Integer ac neque.','2022-07-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('et eros vestibulum ac','Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.','2024-03-31');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mi integer ac neque duis','Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.','2024-08-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet justo morbi ut','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.','2022-08-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisl nunc rhoncus','Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.','2024-03-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('duis at velit eu','Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.','2023-09-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisl nunc nisl duis','Praesent blandit. Nam nulla.','2024-09-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ac tellus semper','Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.','2023-12-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dapibus duis at velit','Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.','2024-09-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('turpis elementum ligula vehicula','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.','2024-04-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('proin at','Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.','2024-04-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('lacus at velit vivamus','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.','2023-10-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('proin','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.','2023-06-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('in quis justo maecenas rhoncus','Suspendisse potenti.','2024-04-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('bibendum imperdiet nullam orci pede','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.','2025-02-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien cum','Suspendisse potenti. In eleifend quam a odio.','2023-12-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec dapibus duis at velit','Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.','2024-10-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('at lorem','Duis bibendum.','2025-05-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('erat curabitur gravida','Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.','2022-11-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('condimentum curabitur','Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.','2023-06-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ante vel','Praesent blandit. Nam nulla.','2024-06-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('elementum nullam varius','Aenean lectus. Pellentesque eget nunc.','2024-01-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sem duis aliquam convallis nunc','Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.','2023-06-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('potenti nullam porttitor lacus','Suspendisse potenti. Nullam porttitor lacus at turpis.','2024-12-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vestibulum','Mauris sit amet eros.','2022-11-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ornare consequat lectus in est','Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.','2025-08-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet lobortis sapien sapien','Duis at velit eu est congue elementum.','2023-11-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('consequat','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.','2024-02-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ullamcorper purus sit amet','Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.','2022-11-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('erat quisque erat eros','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.','2023-06-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vestibulum eget vulputate','Vivamus vestibulum sagittis sapien.','2024-07-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nascetur ridiculus mus etiam','Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.','2023-11-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sed vestibulum sit amet cursus','Etiam faucibus cursus urna. Ut tellus.','2023-01-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('luctus rutrum nulla','Etiam pretium iaculis justo. In hac habitasse platea dictumst.','2025-06-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vulputate','Cras non velit nec nisi vulputate nonummy.','2025-07-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ultrices posuere cubilia','Cras in purus eu magna vulputate luctus.','2024-05-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('primis in faucibus orci luctus','Phasellus in felis. Donec semper sapien a libero. Nam dui.','2024-07-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eget eleifend luctus','Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.','2025-03-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('curabitur at','Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.','2024-07-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mauris','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.','2025-01-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('lacus morbi','Donec dapibus. Duis at velit eu est congue elementum.','2023-05-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('volutpat','Vivamus tortor. Duis mattis egestas metus.','2023-08-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dictumst morbi vestibulum velit id','Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.','2023-02-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('odio porttitor','Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.','2023-07-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mauris','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.','2024-10-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quis turpis eget','Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.','2023-09-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('augue aliquam erat','Nunc purus. Phasellus in felis. Donec semper sapien a libero.','2023-10-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('consectetuer adipiscing elit proin','Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.','2025-03-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ultrices posuere','Etiam vel augue. Vestibulum rutrum rutrum neque.','2023-03-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eros','Aenean lectus. Pellentesque eget nunc.','2022-08-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('volutpat','Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.','2022-07-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet cursus','Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.','2023-06-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('in hac habitasse','Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.','2025-02-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('praesent blandit nam nulla integer','Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.','2024-08-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eget rutrum at lorem','Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.','2023-11-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('duis ac nibh','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.','2023-10-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('est','In sagittis dui vel nisl. Duis ac nibh.','2024-09-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sed interdum venenatis turpis enim','Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.','2023-03-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('non lectus aliquam sit amet','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.','2024-03-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vehicula consequat morbi a','Pellentesque ultrices mattis odio.','2024-04-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nec sem duis','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.','2023-07-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('turpis','Fusce consequat. Nulla nisl. Nunc nisl.','2024-11-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('faucibus cursus urna ut','Phasellus in felis.','2024-01-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quisque porta volutpat erat quisque','Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.','2024-04-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('erat fermentum justo','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.','2022-04-12');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('est lacinia','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.','2023-04-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('facilisi cras non velit','Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.','2022-07-27');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('cum sociis','Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.','2022-07-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('proin eu mi','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.','2023-05-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vestibulum aliquet','Donec dapibus. Duis at velit eu est congue elementum.','2023-03-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ut','Suspendisse potenti.','2024-05-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('aliquam lacus morbi quis tortor','Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.','2023-09-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tortor quis turpis sed ante','Suspendisse accumsan tortor quis turpis.','2024-07-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('at ipsum','In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.','2023-01-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('felis sed interdum venenatis turpis','In quis justo.','2024-07-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('platea dictumst','Donec semper sapien a libero. Nam dui.','2023-02-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('odio in','Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.','2022-08-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eget elit sodales scelerisque','Nam dui.','2023-09-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('at','Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.','2024-10-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('libero rutrum ac lobortis','Etiam justo. Etiam pretium iaculis justo.','2023-05-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('velit vivamus','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.','2024-02-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('diam id ornare imperdiet','Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.','2025-05-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('lacus curabitur at ipsum','Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.','2025-01-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('massa','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.','2023-10-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ornare consequat lectus','Proin at turpis a pede posuere nonummy.','2025-04-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('non pretium','Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.','2024-12-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tincidunt eget','In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.','2022-09-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('morbi odio odio elementum','Morbi vel lectus in quam fringilla rhoncus.','2022-11-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('integer','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.','2024-05-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nibh in hac habitasse platea','Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.','2023-05-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('rutrum','Aenean fermentum.','2024-12-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('odio','Praesent blandit.','2025-06-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec odio justo sollicitudin','Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.','2023-05-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vitae nisi nam','Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.','2022-07-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vestibulum ac est lacinia nisi','In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.','2025-03-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sit amet sapien dignissim','Duis at velit eu est congue elementum.','2023-10-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('convallis eget','Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.','2024-01-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mi','In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.','2024-10-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vitae ipsum aliquam non mauris','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.','2023-01-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('magna at nunc commodo placerat','Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.','2025-06-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('morbi','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.','2022-11-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ridiculus mus vivamus vestibulum sagittis','Nulla ut erat id mauris vulputate elementum.','2022-04-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pede ullamcorper','Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.','2022-11-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('id','Sed ante.','2022-07-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('adipiscing','Suspendisse potenti.','2023-02-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pulvinar lobortis est','Nullam varius. Nulla facilisi.','2023-09-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('aliquet ultrices erat tortor','Nunc purus.','2023-05-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('volutpat eleifend donec ut dolor','Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','2024-11-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('habitasse platea','Aliquam quis turpis eget elit sodales scelerisque.','2025-06-27');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nulla','Maecenas tincidunt lacus at velit.','2023-03-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('congue eget semper rutrum nulla','Duis bibendum. Morbi non quam nec dui luctus rutrum.','2023-10-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tempus semper est quam pharetra','Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.','2023-03-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('aliquet ultrices','Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.','2024-04-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('in tempor turpis nec euismod','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.','2023-09-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('morbi vestibulum velit id','Duis mattis egestas metus.','2024-05-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('odio odio elementum','Phasellus sit amet erat.','2023-02-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sed tristique in tempus sit','Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.','2024-04-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien varius ut blandit','Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.','2022-03-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('penatibus et magnis','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.','2022-08-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('fusce','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.','2024-05-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ut massa volutpat','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.','2024-11-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nullam molestie nibh in','Duis mattis egestas metus.','2023-06-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vel augue vestibulum','Sed accumsan felis.','2023-02-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('porta','Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.','2025-10-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('orci','Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.','2024-10-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('convallis duis consequat dui nec','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.','2024-06-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien varius ut','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','2023-12-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('turpis integer aliquet massa id','Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.','2023-11-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sem praesent id massa id','Nulla tellus.','2024-05-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eget vulputate ut ultrices vel','Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.','2024-01-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nulla ut erat id','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','2022-08-12');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('habitasse platea dictumst','Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.','2025-10-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vel accumsan','Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.','2025-08-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vitae nisi nam','Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.','2023-04-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mattis nibh ligula nec sem','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.','2025-02-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien sapien non mi integer','Integer a nibh. In quis justo.','2022-10-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quam sollicitudin vitae','Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.','2022-05-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('morbi non lectus','Suspendisse potenti.','2023-09-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mattis pulvinar nulla pede','Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.','2023-04-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pellentesque','Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.','2024-06-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ante vel','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.','2025-01-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('viverra eget congue','Mauris ullamcorper purus sit amet nulla.','2023-10-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('curae duis faucibus accumsan odio','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.','2023-03-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('et ultrices posuere cubilia','Nulla facilisi.','2023-05-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dictumst','Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.','2024-11-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('duis bibendum','Nulla justo.','2023-08-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien in sapien iaculis congue','Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.','2024-11-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('id lobortis convallis','In quis justo.','2023-11-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vulputate ut ultrices','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.','2023-06-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('porttitor lacus at turpis','Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.','2023-08-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('in hac habitasse platea','Nulla suscipit ligula in lacus.','2025-05-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('cras','Morbi ut odio.','2022-12-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('posuere cubilia curae','Vivamus tortor. Duis mattis egestas metus.','2025-08-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vestibulum ante','Duis bibendum. Morbi non quam nec dui luctus rutrum.','2024-07-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nunc','Donec dapibus.','2023-11-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('blandit lacinia erat','Morbi vel lectus in quam fringilla rhoncus.','2023-07-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ac enim in','Praesent blandit.','2024-03-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quis tortor id nulla ultrices','Proin eu mi. Nulla ac enim.','2023-06-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pulvinar lobortis est','Vivamus tortor.','2025-10-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('primis','Nam nulla.','2022-05-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisi','Morbi a ipsum.','2023-10-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('justo in hac','Nulla mollis molestie lorem.','2025-12-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('erat quisque erat eros viverra','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.','2022-02-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet','Integer ac neque. Duis bibendum.','2025-04-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vehicula condimentum curabitur','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.','2024-09-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('a libero nam dui','In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.','2023-11-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vehicula condimentum curabitur in libero','Curabitur in libero ut massa volutpat convallis.','2023-11-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quam fringilla rhoncus','Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.','2024-04-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisi','Sed accumsan felis. Ut at dolor quis odio consequat varius.','2024-12-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nonummy','Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.','2025-03-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('fermentum justo nec condimentum','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.','2023-09-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('non interdum in','Nam tristique tortor eu pede.','2024-03-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('et ultrices posuere cubilia','Etiam justo. Etiam pretium iaculis justo.','2024-07-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dui maecenas tristique est et','Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.','2024-12-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('faucibus orci luctus et ultrices','Aenean lectus. Pellentesque eget nunc.','2024-09-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('auctor sed','In hac habitasse platea dictumst.','2022-03-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('adipiscing','Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.','2024-09-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('justo in blandit','In congue. Etiam justo. Etiam pretium iaculis justo.','2022-10-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quis lectus suspendisse potenti in','Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.','2023-02-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eget vulputate ut ultrices','In congue. Etiam justo.','2024-02-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ut volutpat','Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.','2024-01-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nulla','Aenean lectus.','2023-09-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pretium','Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.','2022-04-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eu','Etiam vel augue.','2024-09-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('turpis elementum ligula','In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.','2024-05-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('rutrum neque aenean auctor','Morbi non quam nec dui luctus rutrum.','2022-07-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('massa volutpat convallis morbi','Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.','2022-09-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('morbi ut odio cras mi','Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.','2024-04-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec ut dolor morbi','Sed ante. Vivamus tortor.','2022-03-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet sapien dignissim','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.','2022-11-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('fusce posuere felis sed lacus','In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.','2024-04-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('blandit lacinia erat vestibulum sed','Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.','2024-02-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nam nulla integer','Vivamus vestibulum sagittis sapien.','2023-06-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dictumst aliquam augue quam','Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.','2023-08-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tincidunt eget tempus','Nulla tellus. In sagittis dui vel nisl.','2024-05-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('lorem integer tincidunt','Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.','2024-04-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('lectus in quam fringilla','Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.','2025-07-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sit','Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.','2024-03-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('venenatis turpis','Curabitur in libero ut massa volutpat convallis.','2023-09-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('primis in faucibus orci','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','2024-09-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nulla','Nam tristique tortor eu pede.','2023-06-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quisque erat eros','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','2025-03-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('lacinia sapien quis','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.','2023-12-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('id nulla ultrices aliquet maecenas','Mauris lacinia sapien quis libero.','2024-03-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('congue etiam justo','Mauris ullamcorper purus sit amet nulla.','2022-04-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('consequat lectus in est','Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.','2024-11-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sed justo pellentesque viverra pede','Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.','2025-04-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('duis','In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.','2023-02-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('proin interdum mauris','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.','2023-08-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mollis','Maecenas tincidunt lacus at velit.','2025-01-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('a ipsum integer a','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','2022-12-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisl nunc','Nullam porttitor lacus at turpis.','2023-03-31');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('cubilia curae mauris viverra diam','Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.','2023-01-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('curabitur at ipsum','Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.','2024-03-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('morbi vel lectus in quam','Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.','2025-06-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('et eros vestibulum ac','Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.','2025-05-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nec','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.','2022-05-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('massa id lobortis convallis tortor','Proin leo odio, porttitor id, consequat in, consequat ut, nulla.','2024-05-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quisque porta volutpat erat quisque','Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.','2024-01-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('massa','Suspendisse potenti.','2023-06-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('rhoncus dui vel sem sed','Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.','2025-06-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ultrices posuere cubilia','Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.','2022-07-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('fermentum justo nec condimentum','Nunc purus. Phasellus in felis.','2023-02-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('adipiscing lorem vitae','Vivamus vel nulla eget eros elementum pellentesque.','2024-03-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pede morbi porttitor','Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.','2023-07-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('phasellus id','Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.','2024-05-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('est lacinia nisi venenatis','Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.','2022-09-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet eleifend pede libero quis','Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.','2023-01-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisl','Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.','2022-10-31');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tincidunt lacus','Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.','2024-02-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mauris morbi non lectus','Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.','2023-01-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tellus in sagittis dui vel','Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.','2025-01-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec odio justo','Nulla ut erat id mauris vulputate elementum.','2024-04-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eu sapien cursus vestibulum','Suspendisse potenti.','2024-05-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('volutpat dui maecenas tristique est','Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.','2024-11-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('non quam nec dui','Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.','2023-05-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tincidunt nulla mollis','Integer ac neque.','2025-03-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('suspendisse ornare consequat','Praesent lectus.','2024-05-07');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('felis sed interdum venenatis turpis','Aliquam erat volutpat. In congue.','2024-03-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dolor sit amet consectetuer adipiscing','Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.','2022-11-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien quis libero','Suspendisse potenti. In eleifend quam a odio.','2024-02-12');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('magna','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.','2022-11-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eros elementum','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.','2024-03-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisl nunc','Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.','2025-04-12');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('convallis','Quisque ut erat. Curabitur gravida nisi at nibh.','2023-01-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('scelerisque mauris sit','Donec ut mauris eget massa tempor convallis.','2024-01-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vivamus metus','Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.','2022-06-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('a suscipit nulla','Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.','2025-05-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('suspendisse accumsan tortor','Aliquam quis turpis eget elit sodales scelerisque.','2023-01-31');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('hac','Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.','2023-11-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('justo nec condimentum','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.','2024-02-22');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dictumst maecenas ut massa','Duis bibendum. Morbi non quam nec dui luctus rutrum.','2025-05-31');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('in','Maecenas rhoncus aliquam lacus.','2023-05-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('iaculis diam erat','Praesent blandit.','2023-05-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ipsum aliquam non','Phasellus sit amet erat. Nulla tempus.','2024-09-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tellus in','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.','2025-01-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eget vulputate','Aliquam sit amet diam in magna bibendum imperdiet.','2023-02-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('vestibulum sed magna at','Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.','2023-03-31');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ullamcorper purus sit amet','Vestibulum ac est lacinia nisi venenatis tristique.','2025-10-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pede justo','Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.','2022-09-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pede venenatis non sodales','Sed ante. Vivamus tortor.','2023-02-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('primis in faucibus orci luctus','Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.','2024-04-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('congue etiam','Fusce posuere felis sed lacus.','2024-09-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sed tristique in tempus','Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.','2024-01-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet','Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.','2023-04-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('leo','Nullam varius.','2025-01-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('semper porta volutpat quam pede','Vestibulum sed magna at nunc commodo placerat.','2023-06-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ut mauris eget massa tempor','Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.','2022-09-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('accumsan tortor quis turpis sed','Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.','2022-07-27');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('porttitor lorem id ligula suspendisse','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.','2023-07-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('in','Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.','2023-02-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sem praesent id','In blandit ultrices enim.','2023-04-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ultrices','Morbi porttitor lorem id ligula.','2023-03-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pede ac diam','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.','2023-10-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ac leo','Aenean sit amet justo.','2025-02-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('consectetuer adipiscing','Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.','2023-12-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('feugiat et eros','Nulla mollis molestie lorem. Quisque ut erat.','2022-02-10');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('aenean lectus','In congue. Etiam justo. Etiam pretium iaculis justo.','2024-02-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('curae mauris viverra','Nam dui.','2025-06-27');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('rutrum ac lobortis','Maecenas pulvinar lobortis est.','2022-07-12');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('etiam vel augue vestibulum rutrum','Ut at dolor quis odio consequat varius. Integer ac leo.','2024-01-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('aliquet maecenas leo','In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','2024-04-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet justo morbi ut odio','Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.','2023-06-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('montes nascetur ridiculus mus','Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.','2023-09-14');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('cursus id','Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.','2022-09-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('fermentum donec ut mauris eget','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.','2025-08-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('enim in','Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.','2023-10-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quis orci','Nulla ut erat id mauris vulputate elementum. Nullam varius.','2024-08-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('duis at velit','Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.','2024-01-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('et ultrices posuere cubilia','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.','2023-11-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ultrices','Aliquam quis turpis eget elit sodales scelerisque.','2024-10-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('metus','Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','2023-06-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('enim leo','Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.','2023-12-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('elementum','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.','2023-02-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('posuere nonummy integer non','Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.','2023-05-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tincidunt eget tempus vel pede','Aliquam erat volutpat. In congue.','2024-12-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('amet nulla quisque arcu','Morbi a ipsum.','2023-07-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sapien placerat','In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.','2023-12-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('cras pellentesque','Etiam faucibus cursus urna. Ut tellus.','2023-01-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('imperdiet nullam orci pede','Curabitur at ipsum ac tellus semper interdum.','2024-04-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nisl nunc rhoncus dui vel','In eleifend quam a odio. In hac habitasse platea dictumst.','2024-05-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('elit proin interdum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.','2023-12-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sed tincidunt eu','Morbi porttitor lorem id ligula.','2023-11-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ante','Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.','2024-12-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('cursus id turpis integer aliquet','In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.','2025-06-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sagittis sapien','Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.','2025-03-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('diam nam tristique tortor eu','Curabitur gravida nisi at nibh.','2025-07-08');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sagittis dui vel nisl duis','Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.','2025-02-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('etiam justo','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.','2024-07-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('luctus et','In hac habitasse platea dictumst.','2023-01-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('adipiscing lorem vitae mattis nibh','Nullam porttitor lacus at turpis.','2023-12-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec ut dolor morbi vel','Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.','2023-11-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tellus in sagittis dui vel','Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.','2023-06-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec vitae nisi','Maecenas rhoncus aliquam lacus.','2024-12-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('felis ut at dolor','In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.','2022-03-21');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tellus','Phasellus in felis. Donec semper sapien a libero.','2024-10-24');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('eu est','Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.','2025-02-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('primis in faucibus orci','Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.','2023-09-27');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nascetur ridiculus mus','Morbi vel lectus in quam fringilla rhoncus.','2025-08-25');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tincidunt ante vel ipsum praesent','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','2025-09-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pharetra magna vestibulum aliquet ultrices','In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.','2025-06-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('est risus','Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.','2025-06-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('odio curabitur','Morbi non lectus.','2023-04-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pellentesque volutpat dui maecenas tristique','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.','2024-07-04');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('integer ac leo pellentesque','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.','2022-10-15');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pretium iaculis diam erat fermentum','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.','2023-10-20');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sollicitudin vitae consectetuer','Etiam vel augue.','2023-06-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nec nisi vulputate','Nunc nisl.','2022-04-30');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('morbi porttitor lorem id ligula','Proin eu mi.','2022-11-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('posuere felis','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.','2025-02-09');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('dui','Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.','2025-02-06');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quam a odio in','Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.','2024-04-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ornare','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.','2023-08-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('enim blandit mi in','Duis bibendum. Morbi non quam nec dui luctus rutrum.','2023-05-29');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('pulvinar','In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.','2023-01-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quis tortor id','Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.','2024-09-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('massa','Integer a nibh.','2022-08-17');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mattis','Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.','2023-11-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nulla tempus vivamus in felis','Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.','2024-05-16');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('tincidunt nulla mollis molestie lorem','Integer ac leo.','2024-03-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sociis natoque penatibus et','Morbi a ipsum. Integer a nibh. In quis justo.','2023-02-26');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('quam fringilla rhoncus mauris','Nullam sit amet turpis elementum ligula vehicula consequat.','2023-08-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('luctus nec molestie','In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.','2024-12-27');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('congue','Fusce consequat. Nulla nisl. Nunc nisl.','2025-12-05');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('mattis nibh ligula','Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.','2023-05-18');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('fermentum justo','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.','2024-02-13');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('luctus ultricies eu nibh quisque','Suspendisse potenti. In eleifend quam a odio.','2023-02-11');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('felis','Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.','2022-12-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('sit amet consectetuer adipiscing','Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.','2023-11-23');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('donec ut dolor morbi vel','Aliquam quis turpis eget elit sodales scelerisque.','2023-02-03');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('nunc purus phasellus in','Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.','2024-08-01');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('posuere cubilia curae','Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.','2024-10-19');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('consectetuer','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.','2023-10-28');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ultricies','Nullam porttitor lacus at turpis.','2023-06-02');
INSERT INTO Collection(listName,description,dateCreated) VALUES ('ante vestibulum ante ipsum primis','Pellentesque at nulla. Suspendisse potenti.','2023-11-19');
