INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Buckie Falla','1976-06-29','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gracie Chave','1978-12-14','In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Russ Soans','1984-02-14','Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lancelot Andrini','1982-06-10','Pellentesque ultrices mattis odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Denise Mouan','1974-06-04','In sagittis dui vel nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Salomi Alfonsetti','1997-07-25','Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Westleigh Penk','1987-01-01','Sed ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gaylor Este','1977-10-08','Morbi non quam nec dui luctus rutrum. Nulla tellus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ogden Cheesley','1992-06-25','Etiam pretium iaculis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gran Bonnor','1997-12-24','Morbi non quam nec dui luctus rutrum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Janice Bednall','1986-04-22','Nulla tellus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Dar Blockley','1989-10-09','Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Martie Jaquet','1968-10-14','Pellentesque at nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cal Rounsefell','1963-08-06','Praesent blandit lacinia erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Feodor Flahy','1963-04-17','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Emalia Bingley','1994-01-18','Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Liza Boraston','1990-12-24','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Christian Nellies','1999-11-19','Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sharl Mallinson','1972-08-28','Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('James Krebs','1963-07-29','Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Benjamin Muldoon','1997-10-21','Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Wallie O''Halleghane','1989-08-25','Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jo Flanne','1985-09-17','Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Merv Fuente','1990-12-21','Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Hodge Ireson','1999-09-25','Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Buckie Pallaske','1969-02-26','Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Minna Kroll','1996-09-01','Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cecilio Thebeaud','1971-10-25','Morbi a ipsum. Integer a nibh. In quis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bern Wackley','1968-11-14','Proin risus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Saidee Balaizot','1966-01-15','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Roddie Pinfold','1981-09-24','Vivamus in felis eu sapien cursus vestibulum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Buck Cramer','1965-09-25','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Archibold Hymas','1968-11-29','Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Mischa Capeling','1985-10-10','Nulla tempus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Garrard Dosdell','1965-12-12','Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Richard Dionisii','1981-06-14','Proin risus. Praesent lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Blaine Midson','1968-06-04','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Blair Tsar','1967-09-10','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Whitman Riquet','1967-11-03','Quisque ut erat. Curabitur gravida nisi at nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Wyatt Worswick','1994-07-31','Aenean auctor gravida sem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Braden Pallaske','1996-12-05','Suspendisse potenti.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tallou Esilmon','1977-09-25','Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kaye Fossitt','1969-06-24','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ignatius Heliot','1996-02-22','Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cyndy Addionizio','1993-10-20','In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Emmalynne Piser','1972-01-09','Nulla nisl. Nunc nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Pippa Panas','1965-12-17','Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gale Flindall','1965-03-23','Nullam sit amet turpis elementum ligula vehicula consequat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Brittne Murden','1987-10-26','Aenean sit amet justo. Morbi ut odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sloan Habble','1971-05-07','Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ginnifer Lorroway','1997-07-02','In sagittis dui vel nisl. Duis ac nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carole Dibdale','1968-07-30','Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Richmound Snawden','1983-03-26','In congue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Fletch Teasdale','1992-12-27','Donec posuere metus vitae ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Pierrette Stobbe','1970-03-21','Etiam pretium iaculis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Starlene Bernardi','1967-05-30','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ogdon M''Quhan','1987-07-27','In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jacintha Wheatman','1991-12-12','Nulla suscipit ligula in lacus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cybill Cundict','1976-04-25','Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Consuelo Dearl','1999-08-28','Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sebastiano Farnie','1969-08-05','Vivamus tortor.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carmine Esland','1977-10-06','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Euphemia Spiteri','1994-05-06','In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Celestyna Sandle','1980-11-06','Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Annabell Oldham','1995-10-13','Aenean fermentum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Aviva Scadding','1977-08-23','Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Brandea Whotton','1971-01-30','Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Eldredge Itzakovitz','1960-05-13','Maecenas ut massa quis augue luctus tincidunt.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Stephanus Lain','1981-12-04','In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Judas Scatcher','1990-05-04','Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Monte Wolledge','1981-06-18','In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sidnee Firpi','1997-09-11','Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rinaldo Wellstood','1961-12-24','In congue. Etiam justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Hussein Blackboro','1983-07-03','Aenean lectus. Pellentesque eget nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Albina Mesant','1991-04-20','In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Clarine Heare','1980-01-06','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Adrienne Lightoller','1978-09-03','Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tiphanie Battisson','1979-01-15','Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Dianna Dannohl','1997-07-06','Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Dasie Aicheson','1986-08-24','In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Happy Scranny','1998-05-17','Donec semper sapien a libero. Nam dui.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lacey Chapelhow','1995-03-16','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bertina Croad','1982-08-06','Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Katusha Hedger','1992-05-10','Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Corliss Hourston','1971-05-11','Proin eu mi. Nulla ac enim.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Aubrey Penquet','1963-06-17','Morbi vel lectus in quam fringilla rhoncus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Deirdre Peacham','1991-06-01','Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Herculie Glasby','1966-03-21','In quis justo. Maecenas rhoncus aliquam lacus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ingmar Meldrum','1969-04-19','Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Velvet Lumsdale','1963-09-22','Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Orelia Scrinage','1972-03-17','Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Muffin Mulran','1996-10-19','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kaela Allanson','1988-02-09','Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Yorker Coole','1991-04-25','Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Thurstan Mazonowicz','1974-07-09','Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lilith Gages','1974-06-19','In eleifend quam a odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Iorgos Lamas','1994-06-16','Aenean auctor gravida sem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Morgen Lambden','1969-10-31','Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Judye Stones','1960-01-30','In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Urbano Sowden','1980-05-08','Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rhoda Furzey','1981-11-24','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Keane Gayne','1988-02-07','Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gunar Hammelberg','1968-03-11','In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lennard Jahndel','1992-10-28','Fusce consequat. Nulla nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cathie Bartalucci','1995-10-16','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Violante Pole','1979-04-17','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Zerk Danneil','1975-02-25','Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ivar Keneforde','1993-03-03','Ut tellus. Nulla ut erat id mauris vulputate elementum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Benedetta Peteri','1971-04-06','Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Robin Di Gregorio','1978-07-05','Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Seline Corcoran','1998-01-30','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tiphani Weathers','1985-12-10','Morbi non quam nec dui luctus rutrum. Nulla tellus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lezley Streather','1973-09-02','Maecenas ut massa quis augue luctus tincidunt.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bary Satterthwaite','1974-11-17','Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Emmey Tampling','1975-11-12','Curabitur gravida nisi at nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Olimpia Bossel','1993-03-22','In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Zarah Houndson','1989-07-10','Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Charline Worters','1989-03-28','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gustie Venour','1966-02-13','Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Briana Aries','1972-03-09','Proin eu mi.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('George Toon','1983-06-05','Phasellus id sapien in sapien iaculis congue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Danyelle Dog','1980-12-01','Nulla tempus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Wayland Crown','1967-03-21','Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Nessie Putson','1997-03-17','Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Andreana Broggio','1976-04-23','Aenean lectus. Pellentesque eget nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lyn Atter','1988-06-18','Pellentesque at nulla. Suspendisse potenti.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Evelyn Hocking','1969-05-03','Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tristan De Domenici','1981-10-10','Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Andy Cowup','1996-04-29','Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kissiah Myall','1967-05-19','In quis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bobina Hayward','1973-08-16','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Damara Shearman','1966-06-01','Phasellus sit amet erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lisle Hedditch','1991-04-16','Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Colman Coupar','1977-06-22','Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ashli Bloschke','1998-05-07','Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Peder Gregersen','1973-05-17','Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Alister Saxby','1996-03-31','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Marion Eskrigge','1997-05-26','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Arleen Caesman','1977-01-17','Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Warner Eytel','1974-03-27','Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Morse Blagden','1990-06-22','Donec posuere metus vitae ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Terrance Grinishin','1997-08-30','In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lindy Size','1999-09-02','Nulla tellus. In sagittis dui vel nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Si Inge','1997-10-21','Nulla ut erat id mauris vulputate elementum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Beck MacCracken','1990-08-14','Aliquam non mauris.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kirsten Chugg','1980-08-25','Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Daniela Siddaley','1973-05-09','Aenean lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bendite Gulk','1987-02-01','Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Henrie Cammomile','1966-02-17','Sed ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Shalne Farlow','1968-05-04','Mauris lacinia sapien quis libero.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Roderich Ingre','1972-04-27','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Shelby Cocher','1966-03-19','Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Giuditta Esposita','1980-11-27','Proin eu mi.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Merrill Ingolotti','1972-04-13','Donec dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cassandry Sollars','1988-02-24','Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sarita Byart','1995-01-23','Morbi a ipsum. Integer a nibh. In quis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sigmund Pitone','1994-05-11','In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kimmy Hazeley','1985-10-30','In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Marlon Wetter','1968-01-27','Duis mattis egestas metus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Riobard Willsmore','1986-10-03','Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lesly Garraway','1972-08-09','Fusce consequat. Nulla nisl. Nunc nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Olenka Banville','1967-11-16','Aliquam non mauris. Morbi non lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Skyler Castlake','1961-11-09','Donec dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Anstice Sleeny','1993-03-17','Donec semper sapien a libero. Nam dui.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cris Blondell','1965-06-21','Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Winnifred Folk','1978-07-26','Donec dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Calley Corston','1988-03-28','Donec posuere metus vitae ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lanna Olver','1976-12-23','Suspendisse accumsan tortor quis turpis. Sed ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rodina Langlais','1988-05-10','Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Uta Dufaur','1983-09-26','Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jaclyn Reightley','1971-05-03','Morbi non lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sabrina Risely','1978-01-14','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Stella Briance','1997-12-27','Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Dede Dunphy','1963-02-05','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Silvester Shovelin','1976-10-12','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Amerigo Hilldrop','1970-10-12','Curabitur convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bertrando Cobbled','1997-11-28','Proin risus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Burr Wallage','1996-12-04','Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sancho Plinck','1960-10-20','In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Robb Sanham','1973-01-21','Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Mar de Keyser','1977-09-30','Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Mauricio Seymark','1993-11-04','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Parnell Coale','1983-09-14','Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carole McCluney','1999-04-21','Aenean sit amet justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Melisent Itskovitz','1983-08-05','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Stefano Simner','1982-09-30','In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Nicholle Mc Dermid','1998-11-05','Sed sagittis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Putnem Osbourn','1991-04-10','In sagittis dui vel nisl. Duis ac nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Emmalynne Shadfourth','1970-07-06','Curabitur in libero ut massa volutpat convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Minda Andrey','1992-01-11','Nulla justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jesus Randalston','1992-03-23','Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sauncho Taffs','1960-11-25','Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Suzy Rigolle','1985-07-12','Donec posuere metus vitae ipsum. Aliquam non mauris.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Halie Temlett','1997-01-08','Aliquam non mauris.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gunar Phippen','1979-03-03','Vestibulum ac est lacinia nisi venenatis tristique.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kaile Bispham','1992-06-30','In congue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Malvina Caplan','1962-12-06','Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Baudoin Lammertz','1988-07-23','Nulla justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tiffany Dickman','1989-06-17','Sed ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Prudence Kiebes','1964-09-04','Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cyndy Clout','1994-01-06','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Thorin Hidderley','1982-01-16','Proin at turpis a pede posuere nonummy. Integer non velit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Barbabra Mayne','1990-03-27','Proin at turpis a pede posuere nonummy.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Pansy de Werk','1982-07-21','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Maury Cisland','1965-03-01','Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Webb Cornish','1991-03-28','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Barron Deakan','1983-05-01','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sal Dudding','1994-08-19','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carver Gatty','1967-09-03','Phasellus sit amet erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Adriana Hazell','1993-09-21','In eleifend quam a odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cobby Clamp','1969-03-05','Donec semper sapien a libero. Nam dui.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bard Ellams','1961-06-17','Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Muffin Charge','1996-04-17','Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cam Drennan','1992-05-18','Aliquam non mauris.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Hasheem Sherington','1973-06-19','Suspendisse accumsan tortor quis turpis. Sed ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Galven Iacomini','1979-03-23','Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jeremias O''Luby','1983-03-30','Vivamus vel nulla eget eros elementum pellentesque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Griffy Vanyukov','1982-05-03','Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jamill Haddon','1994-05-18','Nullam molestie nibh in lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Hyacinth Cornfield','1962-02-24','Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Chaddy Hugnet','1995-01-02','Quisque ut erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tova Deuss','1967-03-03','Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Waverly Plant','1997-05-05','Suspendisse ornare consequat lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jarrod Anfusso','1975-05-26','Ut tellus. Nulla ut erat id mauris vulputate elementum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Charlot Manifield','1972-10-22','Duis mattis egestas metus. Aenean fermentum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gertrudis Kitchenman','1968-08-09','Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ryun McIlenna','1985-10-05','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Berk Gullick','1985-08-30','Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Theda Ethelstone','1991-07-29','Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kelly Benger','1983-11-11','Quisque ut erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kay Woolager','1984-01-29','Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Waly Elsie','1962-10-18','Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Quintin Mayell','1996-08-27','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gae Aucoate','1979-08-19','Donec posuere metus vitae ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Thornton Etchingham','1973-06-29','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Piggy Tattam','1991-08-30','Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Minny Rymill','1978-12-29','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Noreen Allgood','1997-05-26','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Graig Roundtree','1963-02-17','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kata Di Pietro','1994-08-11','In congue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Humfrid Stallan','1976-03-09','Aenean lectus. Pellentesque eget nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Katlin Hoy','1979-06-10','Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Heidi McKew','1964-02-21','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lorenza Ivell','1969-02-09','In eleifend quam a odio. In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Willetta Lackemann','1969-11-10','Proin at turpis a pede posuere nonummy.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Joana Sanchis','1983-09-19','Duis mattis egestas metus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Brandie Piken','1977-10-20','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Vernen Gownge','1983-08-08','Praesent lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carrissa Tappor','1998-05-04','Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bibi Colisbe','1972-11-23','Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Witty Speachley','1960-01-05','Sed ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ingar Filipczak','1971-08-17','Pellentesque at nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tabina Fairbrace','1967-12-13','Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sile Ferebee','1974-10-10','Praesent blandit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sydelle Alessandretti','1995-11-11','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Zebulen Tournay','1986-09-30','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Michal Drescher','1994-02-15','Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Eudora Bickle','1995-03-17','Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Nicol Hounsham','1962-02-27','Morbi quis tortor id nulla ultrices aliquet.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lavina Brozek','1992-08-11','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Abrahan Matton','1980-12-04','Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Man McCullouch','1965-12-20','Morbi a ipsum. Integer a nibh. In quis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Pyotr Kornacki','1998-07-13','Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sarah Cosgriff','1983-01-04','Praesent blandit lacinia erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Basil Tulleth','1970-07-26','Nulla ut erat id mauris vulputate elementum. Nullam varius.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Emmery Coyne','1972-05-06','Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bayard Wigley','1973-02-14','Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Eziechiele Chasemoore','1989-07-21','Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Husain Johansson','1973-09-09','Integer ac neque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Judon Kroll','1974-10-24','Etiam justo. Etiam pretium iaculis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rod Warner','1981-07-18','Pellentesque eget nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cassondra Kilner','1968-11-18','Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Mindy Mallatratt','1997-12-10','In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ryan Twelves','1981-11-12','Aliquam sit amet diam in magna bibendum imperdiet.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Edgard Brucker','1974-06-02','Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Herculie Adamovitch','1974-01-01','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Broddy Ouver','1971-04-05','Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Brannon Leblanc','1968-03-20','Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tilda Reschke','1994-06-03','Praesent lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Shanie Parres','1976-12-26','Pellentesque ultrices mattis odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cirillo Armand','1997-03-24','Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Amory Artois','1973-03-25','Integer a nibh. In quis justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ulrika Zottoli','1976-07-24','Sed vel enim sit amet nunc viverra dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Daloris Vynehall','1962-06-30','Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Fayette Grewer','1986-03-01','Nulla ut erat id mauris vulputate elementum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bonni Dantesia','1961-01-28','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gerry Alred','1986-03-28','Nullam sit amet turpis elementum ligula vehicula consequat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lorne O''Shaughnessy','1970-12-15','Aliquam erat volutpat. In congue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kaia Matskiv','1966-08-24','Vestibulum ac est lacinia nisi venenatis tristique.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Marshall Mackilpatrick','1963-04-14','Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jammie Bebbington','1984-07-31','Donec ut mauris eget massa tempor convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Joycelin Percifer','1970-04-30','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Leland Stealfox','1982-02-06','Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Marilyn Lashford','1961-05-09','Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Star Worviell','1989-03-19','Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lindy Flatte','1998-06-17','Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Melicent Davidwitz','1971-07-13','Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Joella Millthorpe','1986-10-23','Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Henry Blitz','1970-03-11','Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Silas O''Moylan','1965-11-02','Suspendisse potenti.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bradan Segrott','1973-12-02','In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Wald Ricardet','1989-09-06','Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jessalyn Gibbings','1982-12-07','Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tomas Bruinsma','1974-06-03','Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jorge Longworthy','1964-11-30','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kaila Cadreman','1989-01-20','Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Wolfie Figgen','1994-07-02','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Wallace Valens-Smith','1967-11-25','Pellentesque at nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rene Philbrook','1997-06-01','Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tabby Desbrow','1960-06-06','Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Florencia Roches','1968-07-17','Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cecile Beckensall','1965-10-19','Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sue Cheal','1989-01-20','Integer non velit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carey Sayers','1995-07-30','In quis justo. Maecenas rhoncus aliquam lacus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carmon Steinhammer','1977-03-20','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Maddie Mackelworth','1960-07-19','Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Valentijn Deniset','1992-03-01','Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Zabrina Bastock','1970-04-21','Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Sile Dimitru','1978-08-02','Aliquam sit amet diam in magna bibendum imperdiet.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Clio Rayburn','1966-06-01','Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Randie Bote','1968-06-18','Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Alfie Boomes','1984-09-09','Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Hazel Wheelan','1988-12-30','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Crystal Jery','1967-06-15','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tamera Hatherall','1965-05-27','Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Floyd Kynder','1967-01-31','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Anabella Kennally','1997-05-29','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Prudy Gellately','1997-11-27','Donec ut dolor.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Aylmar Vasyukhichev','1987-03-24','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kyla Hought','1986-10-12','Morbi a ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gwen Belle','1997-04-14','Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Northrup Figures','1983-12-31','Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Valentine Brastead','1996-09-13','Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lynelle Jakes','1995-03-07','Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Britni Cuerda','1993-03-02','Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tobi Branford','1997-10-12','Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Carce Tilbrook','1992-10-26','Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jude Bernadon','1966-08-05','Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Meade Kenset','1973-03-07','Integer ac neque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Corilla Dracey','1998-01-19','Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Winnie Piddlesden','1995-04-29','Proin at turpis a pede posuere nonummy. Integer non velit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Melisa Southern','1995-01-31','Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Simona Oxbury','1979-05-26','Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Godwin Jereatt','1971-07-15','Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Morly McSherry','1962-06-06','Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Christoph Cosely','1990-06-23','Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Winna Gunnell','1973-04-07','In hac habitasse platea dictumst.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Florenza McGrae','1961-03-31','Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Yuri Wakelam','1989-08-01','Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ozzie Bucklee','1986-06-26','Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Cynthia Blance','1969-10-26','Morbi a ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Doris Knoble','1989-02-24','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Arlan Sporton','1971-06-23','Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Huntington Plume','1990-09-23','Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Henka Bransom','1991-04-20','Ut tellus. Nulla ut erat id mauris vulputate elementum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Stu Abbet','1982-06-10','Duis bibendum. Morbi non quam nec dui luctus rutrum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Obidiah Shillabear','1986-12-11','Proin eu mi. Nulla ac enim.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Darcy Malster','1988-11-15','Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Noach Mayers','1960-10-31','In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kaile Rotte','1963-12-11','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Dorisa Baynard','1990-06-18','Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Benedicta Chopy','1985-06-23','Sed ante.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tyrus Lockner','1979-11-15','Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tobias Mungan','1999-03-09','Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Lenci Kleehuhler','1996-04-30','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Chester Piel','1991-09-18','Vivamus tortor. Duis mattis egestas metus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Tim Laverock','1965-07-27','Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Shoshana Borthe','1990-11-06','Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Marie Watmough','1980-11-13','Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Marilee Longhorne','1981-07-02','Curabitur in libero ut massa volutpat convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kass Higbin','1961-12-05','Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Frants Oen','1999-02-27','Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Taite Leibold','1997-09-28','Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Fred Hutcheons','1962-05-12','Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rockey Bucher','1976-01-01','Ut at dolor quis odio consequat varius.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Ryon Haddon','1998-01-29','In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Felecia Carbine','1998-05-13','Duis bibendum. Morbi non quam nec dui luctus rutrum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Augustin Aleksankin','1994-11-13','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Inglis Barrand','1970-04-15','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Alic Hagston','1991-01-24','Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Dacey Edgington','1979-01-18','Nulla ut erat id mauris vulputate elementum. Nullam varius.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Neal Winters','1975-10-31','Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Westley Wheatman','1969-07-07','Nulla tempus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Graig Akerman','1982-04-15','Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rasia Garrique','1967-03-14','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Magnum Houldcroft','1981-04-25','Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Hertha Shills','1996-11-06','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Jodee Stanbro','1964-01-23','Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Kendal Whaites','1968-11-21','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Emelita Oriel','1976-03-24','Morbi porttitor lorem id ligula.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Bink Elphey','1961-03-07','Fusce consequat. Nulla nisl. Nunc nisl.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Harman Longhorne','1970-12-28','Aenean sit amet justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Davin Gallie','1970-04-12','Phasellus in felis.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gay Roskell','1989-08-01','Morbi vel lectus in quam fringilla rhoncus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Gertrude Rawll','1974-08-08','In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Viole Tapping','1979-08-17','Ut tellus.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Terry Webber','1969-12-29','Aliquam erat volutpat. In congue. Etiam justo.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Delphine Paxforde','1968-06-15','Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Miles Dewane','1971-11-29','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
INSERT INTO Director(name,dateOfBirth,biography) VALUES ('Rodger Revening','1976-01-24','Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
